### ISSUE TITLE
Authentication errors on CircleCI/GCP

### ISSUE THREAD

**Issue by arokem** [pangeo-data/example.pangeo.io-deploy#6]
I set up things according to the README, and still getting an authentication error on CircleCI in the "Build primary image if needed", when it is trying to run `hubploy-image-builder`: 

```
#!/bin/bash -eo pipefail
hubploy-image-builder \
  --push \
  --registry-url https://us.gcr.io \
  --registry-username _json_key \
  --registry-password "${GCR_READWRITE_KEY}" \
  --repo2docker \
  deployments/${DEPLOYMENT}/image/ ${IMAGE_NAME}
Traceback (most recent call last):
  File "/root/repo/venv/lib/python3.6/site-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/root/repo/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://35.237.221.205:2376/v1.35/distribution/us.gcr.io/learning-2-learn-221016/example-pangeo-io-notebook:2b306e1/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/repo/venv/bin/hubploy-image-builder", line 11, in <module>
    load_entry_point('hubploy==0.1.0', 'console_scripts', 'hubploy-image-builder')()
  File "/root/repo/venv/lib/python3.6/site-packages/hubploy/imagebuilder.py", line 151, in main
    if needs_building(client, args.path, args.image_name):
  File "/root/repo/venv/lib/python3.6/site-packages/hubploy/imagebuilder.py", line 22, in needs_building
    image_manifest = client.images.get_registry_data(image_spec)
  File "/root/repo/venv/lib/python3.6/site-packages/docker/models/images.py", line 333, in get_registry_data
    attrs=self.client.api.inspect_distribution(name),
  File "/root/repo/venv/lib/python3.6/site-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/root/repo/venv/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/root/repo/venv/lib/python3.6/site-packages/docker/api/image.py", line 266, in inspect_distribution
    self._get(self._url("/distribution/{0}/json", image)), True
  File "/root/repo/venv/lib/python3.6/site-packages/docker/api/client.py", line 262, in _result
    self._raise_for_status(response)
  File "/root/repo/venv/lib/python3.6/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/root/repo/venv/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication")
Exited with code 1
```

Do I need to edit the `secrets/staging.yaml` file in some way? I am using my own GCP account, not the one y'all have, so maybe that's the issue?

**Comment by arokem** [comment]
Also, the [documentation for hubploy](https://github.com/yuvipanda/hubploy/blob/master/docs/image-builder.rst) (such as it is) suggests that we need a Dockerfile in there. I assume that this is incorrect (see also #5)? That directory can be anything that repo2docker understands?

**Comment by jhamman** [comment]
Yes, @arokem, anything that repo2docker understands. In talking with @yuvipanda, it sounds like the hubploy docs are a little out of date and he is going to be updating them soon.

_I don't know how to answer your secrets question so hopefully someone else chimes in_
